version: '3.8'

services:
  mysql:
    container_name: mysql-clean-architecture
    image: nxrm.corp.bdc.ca:4445/library/mysql:8.0 # mysql:latest
    environment:
      MYSQL_DATABASE: clean-architecture-db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      ACCEPT_EULA: true
      MYSQL_TCP_PORT: 3309
    #    volumes:
    #      - mysql-data:/var/lib/mysql
    ports:
      - "3309:3309"
    restart: always